from pathlib import Path
import json,hashlib,datetime
root=Path('.');out=root/'artifacts/prefix_io_v1/server08-p4-01-cpu'
def ref(p):
 raw=p.read_bytes();return {'path':str(p),'bytes':len(raw),'sha256':hashlib.sha256(raw).hexdigest()}
main=json.loads((out/'current-integration-01/result.json').read_text());patch=json.loads((out/'patch-roundtrip-01/result.json').read_text());review=json.loads((out/'audit-review/p4-cpu-static-review-v2.json').read_text());preserve=json.loads((out/'final-input-and-P3-preservation.json').read_text())
assert main['status']=='PASS_P4_CPU_CURRENT_INTEGRATION' and main['unique_counts']=={'passed':1588,'skipped':16,'failed':0} and main['source_lock_unchanged'] and main['ledger_unchanged'] and main['guard_verified']
assert patch['status'].startswith('PASS_') and review['status']=='PASS_CPU_CONTRACT_REVIEW_NOT_FULL_P4_ACCEPTANCE' and preserve['P3_locked_inputs_unchanged']
report=root/'docs/prefix_io_v1/SERVER08_P4_CPU_REPORT.md';assert not report.exists();report.write_bytes((out/'P4_CPU_DELIVERY_REPORT.md').read_bytes())
missing=['D qualified native ETA/uncertainty producer','I/J real paired semantic verifier and qualified production CostTable loader','native production load state, cost-matched quota/batch activation and qualification','new P4 real GPU owner/CUDA/model/live-shadow/overlap/overhead/effect evidence']
summary={'schema_version':1,'status':'P4_CPU_CONTRACT_AND_MOCK_COMPLETE_PRODUCTION_GPU_BLOCKED','created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'CPU_supported_contract_and_mock_scope_complete':True,'full_P4_complete':False,'P3_closed_preserved':True,'CPU':{'unique_passed':1588,'skipped':16,'failed':0,'new_P4_unique_tests':179,'standalone_repeated_runs_added':False,'historical_12_fixtures_rerun':False,'real_Linux_AIO_path_tested':True,'P4_real_GPU_or_model_tested':False},'source':{'tested_P4_inputs':70,'unchanged_before_after':True,'P3_protected_inputs':2724,'unchanged':True,'registered_cache_files':3048,'registered_cache_bytes':2796552192,'unchanged_registered_bytes':True},'GPU':{'new_runs':0,'initialized':False,'availability_probed':False,'availability_report':'user_reported_no_GPU','budget_reserved_seconds':0,'budget_added_seconds':0,'total_seconds':16520.562886646483,'max_hours':8,'ledger_unchanged':True,'downloads_added_bytes':0,'system_changes':False,'cache_merge_or_deletion':False},'production_implementation_complete':False,'positive_method_effect_established':False,'slo_frozen':False,'production_missing_work':missing,'evidence':[ref(out/s) for s in ['P4_CPU_DELIVERY_REPORT.md','CAPABILITY_MATRIX_P4_CPU.md','P4_VERSION_LOCK.json','current-integration-01/result.json','current-integration-01/cpu.xml','current-integration-01/cuda-guard.json','test-input-lock-v2.json','patch-roundtrip-01/result.json','final-input-and-P3-preservation.json','audit-review/p4-cpu-static-review-v2.json','gpu-stage-preparation-v3.json','gpu-launch-denied-v3.json','EXECUTED_COMMANDS.json','REPRODUCE_P4_CPU.md']],'next_allowed_stage':'CPU concrete fixes if found; GPU phase only after explicit scope/availability/storage/budget check; finish P4 production integration and qualification before P5'}
p=out/'P4_CPU_ROOT_CLOSEOUT.json';assert not p.exists();p.write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n')
statepath=root/'experiments/prefix_io_v1/execution_state.json';before=statepath.read_bytes();backup=out/'execution-state-before-p4-cpu-closeout.json';assert not backup.exists();backup.write_bytes(before);state=json.loads(before)
phase=next(p for p in state['phases'] if p['id']=='P4');phase.update(status='cpu_contract_and_mock_complete_production_GPU_blocked',full_stage_complete=False,actual_outputs=[str(report),str(out/'P4_CPU_ROOT_CLOSEOUT.json')],test_evidence=[str(out/'current-integration-01/result.json'),str(out/'patch-roundtrip-01/result.json'),str(out/'audit-review/p4-cpu-static-review-v2.json')])
state.update(status=summary['status'],current_phase='P4_CPU_COMPLETE_GPU_BLOCKED',current_server_blockers=missing+['Current user scope is CPU-only; GPU unavailable per user report'],latest_cpu_test_evidence=str(out/'current-integration-01/result.json'),latest_cpu_passed=1588,latest_cpu_skipped=16,latest_cpu_scope='Current affected implementation regression; 179 new P4 cases, no repeated count, historical cases separate',latest_delivery_report=str(report),current_remaining_work=missing,remaining_work=missing,P4_enabled=False,P4_CPU_enabled=True,P4_GPU_enabled=False,gpu_permission_status='current_CPU_ONLY_scope; historical YAML grant preserved, no new GPU authorization inferred',p4_cpu=summary)
assert all(next(p for p in state['phases'] if p['id']==n)['status'].startswith('not_started') for n in ['P5','P6','P7'])
statepath.write_text(json.dumps(state,ensure_ascii=False,indent=2)+'\n');snapshot=out/'execution-state-after-p4-cpu-closeout.json';assert not snapshot.exists();snapshot.write_bytes(statepath.read_bytes())
receipt={'status':'PASS_P4_CPU_STATE_BACKUP_AND_UPDATE','before':ref(backup),'after':ref(snapshot),'P3_status_unchanged':next(p for p in state['phases'] if p['id']=='P3')['status'],'P4_full_stage_complete':False,'P5_P6_P7_not_started':True,'GPU_ledger_mutated':False}
p=out/'execution-state-p4-cpu-update-receipt.json';assert not p.exists();p.write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps({'status':summary['status'],'root_closeout':ref(out/'P4_CPU_ROOT_CLOSEOUT.json'),'state_update':receipt}))
