from pathlib import Path
import json,time,subprocess,sys,traceback
root=Path("/root/autodl-tmp/prefix-io-v1-handoff/project");d=root/"artifacts/prefix_io_v1/server14-dr-long-20261005"
def wait_closed(label,deadline_seconds):
 started=time.monotonic();leaf=root/"experiments/prefix_io_v1/runs"/label/"result.json"
 while not leaf.exists():
  if time.monotonic()-started>deadline_seconds:raise TimeoutError(label)
  time.sleep(1)
 value=json.loads(leaf.read_bytes())
 if not (value.get("exit")==value.get("child_exit")==0 and value.get("session_drained") is True and value.get("session_members_before_cleanup")==[] and value.get("session_members_after_cleanup")==[] and value.get("timed_out") is False):
  raise RuntimeError("actual run failed; pair stopped: "+label)
 ledger=json.loads((root/"experiments/prefix_io_v1/gpu-budget-ledger.json").read_bytes())
 if ledger.get("active_reservation") is not None:raise RuntimeError("active reservation remains after completed guard")
 print(json.dumps({"closed_run":label,"elapsed_seconds":value["elapsed_seconds"]}),flush=True)
 return value
try:
 wait_closed("server14-dr-cal07",340)
 exec("from pathlib import Path\nimport json,time,hashlib,importlib.util,sys\nroot=Path(\"/root/autodl-tmp/prefix-io-v1-handoff/project\");d=root/\"artifacts/prefix_io_v1/server14-dr-long-20261005\";run=root/\"experiments/prefix_io_v1/runs/server14-dr-cal07\"\nassert (run/\"result.json\").exists()\ng=json.loads((run/\"result.json\").read_bytes());assert g[\"exit\"]==g[\"child_exit\"]==0 and g[\"session_drained\"] and not g[\"timed_out\"],g\ndef ref(p):\n b=p.read_bytes();return dict(path=p.relative_to(root).as_posix(),bytes=len(b),sha256=hashlib.sha256(b).hexdigest())\nrref=ref(run/\"details/result.json\");gref=ref(run/\"result.json\")\nlock=json.loads((d/\"DR_SOURCE_LOCK_05.json\").read_bytes());files={x[\"path\"]:x for x in lock[\"files\"]}\nfor row in (rref,gref,ref(d/\"CONFIG_CAL07.json\")):files[row[\"path\"]]=row\nlock[\"files\"]=sorted(files.values(),key=lambda x:x[\"path\"])\nlock[\"actual_independent_restore_calibration_refs\"]=dict(result_ref=rref,guard_ref=gref)\nlp=d/\"DR_SOURCE_LOCK_07.json\"\nwith lp.open(\"x\") as f:json.dump(lock,f,indent=2,sort_keys=True);f.write(\"\\n\")\nc=json.loads((d/\"METHOD_CONFIG_TEMPLATE_05.json\").read_bytes());c[\"source_lock_ref\"]=ref(lp);c[\"dr_calibration_result_ref\"]=rref;c[\"dr_calibration_guard_ref\"]=gref\ncp=d/\"CONFIG_DR01_02.json\"\nwith cp.open(\"x\") as f:json.dump(c,f,indent=2,sort_keys=True);f.write(\"\\n\")\nsys.path.insert(0,str(root/c[\"runtime_import_roots\"][0]))\nfrom prefix_io_control.p4_restore_forecast import load_restore_calibration,RestoreCalibrationCoverageMissing\ntry:\n cal=load_restore_calibration(root,files,rref,gref,expected_gpu_uuid=c[\"gpu_uuid\"],expected_common_runtime_domain_sha256=c[\"common_runtime_domain_sha256\"],expected_runtime_refs=c[\"runtime_refs\"],now_ns=time.monotonic_ns(),max_age_ns=c[\"history_max_age_ns\"])\n e=dict(status=\"VALID_ACTIONABLE_CALIBRATION\",sample_count=len(cal.samples))\nexcept RestoreCalibrationCoverageMissing as ex:\n e=dict(status=\"VALID_CLOSED_BUT_COVERAGE_MISSING\",reason=ex.reason,sample_count=ex.sample_count,exact_cell_counts=ex.exact_cell_counts)\ne.update(config_ref=ref(cp),source_lock_ref=ref(lp),calibration_result_ref=rref,calibration_guard_ref=gref,gpu_operations=0)\nwith (d/\"ACTUAL_CAL07_LOADER_CPU_RESULT_01.json\").open(\"x\") as f:json.dump(e,f,indent=2,sort_keys=True)\nprint(json.dumps(e))\n",globals())
 exec("\nfrom pathlib import Path\nimport subprocess,json,time,shutil\nroot=Path(\"/root/autodl-tmp/prefix-io-v1-handoff/project\");d=root/\"artifacts/prefix_io_v1/server14-dr-long-20261005\";tag=\"U04\";label=\"server14-dr-long-u04\";cfg=\"artifacts/prefix_io_v1/server14-dr-long-20261005/CONFIG_U07.json\"\nledger=json.loads((root/\"experiments/prefix_io_v1/gpu-budget-ledger.json\").read_bytes());used=ledger[\"gpu_wall_seconds\"]\nassert ledger.get(\"active_reservation\") is None and used>=0\nassert shutil.disk_usage(root).free>=8*1024**3+3*1024**3\nassert not (root/\"experiments/prefix_io_v1/runs\"/label).exists()\nargv=[str(root/\".venv/bin/python\"),\"-B\",str(d/\"run_gpu_stage_standing_v1.py\"),\"--permissions-path\",\"artifacts/prefix_io_v1/server14-dr-long-20261005/EFFECTIVE_UNCAPPED_D_R_GPU_PERMISSION_02.json\",\"--label\",label,\"--seconds\",\"300\",\"--\",str(root/\".venv/bin/python\"),\"-B\",str(d/\"dr_p316_original_adapter_v5.py\"),\"--project\",str(root),\"--config\",cfg,\"--execute\"]\nwith (d/(\"LAUNCH_\"+tag+\"_STDOUT.log\")).open(\"xb\") as out,(d/(\"LAUNCH_\"+tag+\"_STDERR.log\")).open(\"xb\") as err:\n p=subprocess.Popen(argv,cwd=root,stdin=subprocess.DEVNULL,stdout=out,stderr=err,start_new_session=True,close_fds=True)\nvalue={\"argv\":argv,\"pid\":p.pid,\"label\":label,\"config\":cfg,\"launched_unix\":time.time(),\"budget_used_before\":used,\"budget_remaining_before\":None,\"GPU_launch_requested\":True}\nwith (d/(\"LAUNCH_\"+tag+\".json\")).open(\"x\") as f:json.dump(value,f,indent=2)\nprint(json.dumps(value))\n",globals())
 wait_closed("server14-dr-long-u04",340)
 exec("\nfrom pathlib import Path\nimport subprocess,json,time,shutil\nroot=Path(\"/root/autodl-tmp/prefix-io-v1-handoff/project\");d=root/\"artifacts/prefix_io_v1/server14-dr-long-20261005\";tag=\"DR01\";label=\"server14-dr-long-dr01\";cfg=\"artifacts/prefix_io_v1/server14-dr-long-20261005/CONFIG_DR01_02.json\"\nledger=json.loads((root/\"experiments/prefix_io_v1/gpu-budget-ledger.json\").read_bytes());used=ledger[\"gpu_wall_seconds\"]\nassert ledger.get(\"active_reservation\") is None and used>=0\nassert shutil.disk_usage(root).free>=8*1024**3+3*1024**3\nassert not (root/\"experiments/prefix_io_v1/runs\"/label).exists()\nargv=[str(root/\".venv/bin/python\"),\"-B\",str(d/\"run_gpu_stage_standing_v1.py\"),\"--permissions-path\",\"artifacts/prefix_io_v1/server14-dr-long-20261005/EFFECTIVE_UNCAPPED_D_R_GPU_PERMISSION_02.json\",\"--label\",label,\"--seconds\",\"300\",\"--\",str(root/\".venv/bin/python\"),\"-B\",str(d/\"dr_p316_original_adapter_v5.py\"),\"--project\",str(root),\"--config\",cfg,\"--execute\"]\nwith (d/(\"LAUNCH_\"+tag+\"_STDOUT.log\")).open(\"xb\") as out,(d/(\"LAUNCH_\"+tag+\"_STDERR.log\")).open(\"xb\") as err:\n p=subprocess.Popen(argv,cwd=root,stdin=subprocess.DEVNULL,stdout=out,stderr=err,start_new_session=True,close_fds=True)\nvalue={\"argv\":argv,\"pid\":p.pid,\"label\":label,\"config\":cfg,\"launched_unix\":time.time(),\"budget_used_before\":used,\"budget_remaining_before\":None,\"GPU_launch_requested\":True}\nwith (d/(\"LAUNCH_\"+tag+\".json\")).open(\"x\") as f:json.dump(value,f,indent=2)\nprint(json.dumps(value))\n",globals())
 wait_closed("server14-dr-long-dr01",340)
 with (d/"ACTUAL_PAIR_EXECUTION_01.json").open("x") as f:json.dump(dict(status="COMPLETED_GUARDS_REQUIRE_RESULT_ANALYSIS",runs=["server14-dr-long-u04","server14-dr-long-dr01"],finished_unix=time.time(),new_policy_or_workload_changes=False),f,indent=2)
except BaseException as exc:
 traceback.print_exc()
 with (d/"ACTUAL_PAIR_EXECUTION_FAILURE_01.json").open("x") as f:json.dump(dict(status="STOPPED",error_type=type(exc).__name__,error=str(exc),finished_unix=time.time()),f,indent=2)
 sys.exit(1)
